### ISSUE TITLE
1.4.2.2 changelog from 1.4.2.1

### ISSUE THREAD

**Issue by flamby** [Calsoft-Pvt-Ltd/NSX_V2T_Migration_Tool#1]
Hi,

Thanks for open sourcing it. Is it planned to publish changelog between 1.4.2.2 and 1.4.2.1?

Thanks!

**Comment by NSX-V2T-Support** [comment]
Hi @flamby, Release Notes has been added you can check it in the v1.4.2.2 Release section.

**Comment by flamby** [comment]
Thank you very much @NSX-V2T-Support
